name: grove
description: "GROVE — a gamified community wellness platform. MVP prototype."
publish_to: "none"
version: 2.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # State management
  provider: ^6.1.2
  # Local persistence (no backend for prototype)
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/cor_logo.jpg
    - assets/images/cor_logo_transparent.png
